# Generated by Django 4.1.3 on 2022-11-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceCapsules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CapsuleId', models.CharField(max_length=50)),
                ('CapsuleSerial', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('OriginalLaunch', models.DateTimeField()),
                ('Missions', models.CharField(max_length=50)),
                ('Landings', models.IntegerField()),
                ('Type', models.CharField(max_length=50)),
                ('Details', models.CharField(max_length=50)),
                ('ReuseCount', models.IntegerField()),
            ],
        ),
    ]
